version: '3.8'

services:
  frontend:
    image: 793524670489.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:11
    ports:
      - "3000:3000"
    networks:
      - dev-net	
    mem_limit: 512m
    cpus: 0.5
	
  backend:
    image: 793524670489.dkr.ecr.us-east-1.amazonaws.com/bank-backendapi:latest
    ports:
      - "8080:8080"
	networks:
      - dev-net
    	  
